// Auto-generated by scripts/build-articles-data.js
export interface ArticleTOCItem {
  id: string;
  text: string;
  level: 2 | 3;
}

export interface ArticleFAQ {
  question: string;
  answer: string;
}

export interface ArticleBrief {
  primaryKeyword: string;
  secondaryKeywords: string[];
  searchIntent: string;
  targetCustomer: string;
  contentGoal: string;
  outline: string[];
}

export interface ArticleSeo {
  title: string;
  description: string;
  focusKeyword: string;
  canonicalUrl: string;
  ogTitle: string;
  ogDescription: string;
}

export interface ArticleMetadata {
  id: number;
  uuid?: string;
  slug: string;
  title: string;
  category: string;
  categorySlug: string;
  excerpt: string;
  readingTime: string;
  wordCount: number;
  author: string;
  publishedAt: string;
  updatedAt: string;
  featuredImageUrl: string;
  featuredImageAlt: string;
  seo: ArticleSeo;
  briefSummary: {
    searchIntent: string;
    targetCustomer: string;
    contentGoal: string;
  };
  faqCount: number;
  headingsCount: number;
}

export interface ArticleContent {
  slug: string;
  html: string;
  toc: ArticleTOCItem[];
  faqs: ArticleFAQ[];
  brief: ArticleBrief;
  schemaOrg: Record<string, any>;
}

export interface ArticleDetail extends ArticleMetadata, ArticleContent {}

export interface CategoryInfo {
  slug: string;
  name: string;
  description: string;
  count: number;
}
